### PR TITLE
add dark theme (disabled for now, automatically selects light mode) + disable more bindings

### PR DESCRIPTION
**Pull request by eltrevii**

### CODE REVIEW

**Comment by eltrevii** [comment]
@willnode you can merge this pr and the other one too

**Comment by willnode** [comment]
Sorry I haven't got my Windows laptop yet. 

If you sure that it will work I'll merge those as is.

**Comment by eltrevii** [comment]
well i can wait but why dont you have your laptop yet?

**Comment by willnode** [comment]
I work at the town but forgot to bring my windows laptop from home. Going home this weekend to pick it up.

**Comment by eltrevii** [comment]
ok

**Comment by aritz331** [comment]
@willnode please tell me you got the laptop

**Comment by eltrevii** [comment]
@willnode why are you doing this to me

**Review by willnode — APPROVED** [review]

**Pull request merged**
